# Generated by Django 2.2.5 on 2019-09-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuadronvialapi', '0002_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=500)),
                ('correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuadronvialapi.Pregunta')),
            ],
        ),
    ]
