# Generated by Django 2.2.5 on 2019-09-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuadronvialapi', '0006_sesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pregunta', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuadronvialapi.Categoria')),
            ],
        ),
    ]
